Iteration 13 completed
moonicy/gometrics pull request #13
Opened 2024-07-12 15:17 UTC by moonicy

2024-07-16 20:37 UTC, capsulated requested changes
Всё в комментариях. Некоторые комментарии рекомендательные, некоторые обязательные (к примеру, создания подключения в cmd). В целом, там всё написано, думаю, по содержанию будет понятно. Если вдруг нет - смело пиши в чат подгруппы, тегай, и добавляй снипет, всё разберём (либо 1-1, если необходимо)

2024-07-16 20:37 UTC, capsulated commented on internal/handlers/metrics.go
> +func NewStorage(cfg config.ServerConfig, db storage.DB, cr storage.Consumer, pr storage.Producer) Storage {
А, ну вот и абстрактная фабрика. 

Я так понимаю, эта конструкция в `cmd` была именно для закрытия соединения или пинга? Так как этих методов не должно, по идее, быть в других хранилках, то можно их вызывать только в случае того, если в конфиге указан флаг, что используется хранилка. Сделать это можно с помощью приведения типа интерфейса к конкретному:
```go
...
storage := NewStroage(cfg, ...)
if cfg.db {
   storage.(DbStorage).ping()
}
```
Это приблизительный пример, может понадобиться проверка `if storage, ok := storage.(DbStorage); ok { storage.ping() }`, но если мы точно уверены, что тип бд - то, если не ошибаюсь, можно и не проверять. 

Также, можно разделить интерфейсы и проверить, реализует ли созданный тип этот интерфейс, что-то типа того:
```go
_, ok := interface{}(storage).(Pinger)
fmt.Println("Interface implemented: ", ok)
```

Третий вариант, можно придумать какой-то метод, который будет возвращать указатель на структуру, типа `Closer` (или Pinger) или nil. 

Вообще, в этом задание с пингом и закрытием подключения только у БД (хотя у файловой хранилки также можно реализовать), но общим интерфейсом для хранилки памяти и хранилки бд, не тривиальное. И в этом задании я не видел ещё простого и лаконичного решения ))) Можно поэкспериментировать) 

Но из `cmd` создание подключения, в любом случае, нужно убирать )

2024-07-16 20:37 UTC, capsulated commented on internal/handlers/metrics.go
> +func NewStorage(cfg config.ServerConfig, db storage.DB, cr storage.Consumer, pr storage.Producer) Storage {
Только что появилась идея, к примеру, возвращать не только хранилку, а ещё и указатели *Pinger, *Closer:
`NewStorage(...) (Storage, *Pinger, *Closer)` и провять на nil после вызова абстрактной фабрики. Но тоже, не совсем понятно, насколько это 'красиво'  ))

2024-07-16 20:37 UTC, capsulated commented on internal/handlers/updates_json_metrics.go
> +	err = mh.storage.SetMetrics(req.Context(), mtCounter, mtGauge)
Хорошо бы дочерний контекст создать от контекста из запроса

2024-07-16 20:37 UTC, capsulated commented on internal/storage/database.go
> +type DB interface {
Я так понимаю, это дополнительный слой специально для `retry`? В реальной жизни вряд ли понадобится, если мы используем свою БД на своём сервере. Uptime действующих сервисом обычно около 99 с чем-то процентов. В принципе, в облаке может пригодится, вдруг контейнер с БД перезагружается, но обычно есть  репликация. Retry удобен в тех случаях, скажем, когда мы используем БД, как сторонний сервис - SaaS (Software as a service). Это не ошибка, так как в задании это было, скорее для справки. А реализовано классно, как доп уровень абстракции 👍

2024-07-16 20:37 UTC, capsulated commented on internal/storage/database.go
> +	_, err := dbs.db.ExecContext(ctx, `CREATE TABLE IF NOT EXISTS gauge (id serial PRIMARY KEY, name text UNIQUE, value double precision)`)
Такое обычно в init.sql скрипт кладут в конейнере БД - это тоже для справки, так как в нашем случае не получится его добавить из-за автотестов

2024-07-16 20:37 UTC, capsulated commented on internal/storage/database.go
> +	sqlStr += "ON CONFLICT (name) DO UPDATE SET value = EXCLUDED.value"
Собирать строки для запросов - не очень хорошая идея, так как потом менеджерить сложно. Нельзя как-то упростить? Не критично, но можно подумать

2024-07-16 20:37 UTC, capsulated commented on internal/storage/database.go
> +func replaceSQL(old, searchPattern string) string {
А это обязательно? Мы же изначально значем, что у нас postgres и синтаксис будет именно для postgres. В самой библиотеке для работы базы данных нет каких-то настроек, с этим связанных? Просто немного нагружает код и кажется, что можно всё же избавиться от данной конструкции. Комментарий также не сильно критичный, но желательный для исправления (если возможно)

2024-07-16 20:37 UTC, capsulated commented on internal/storage/file.go
> +func (fs *FileStorage) Init(ctx context.Context) error {
Это в конструктор переместить хорошо бы, это же связано с инициализацией. В конструкторе обычно все init'ы и происходят

2024-07-16 20:37 UTC, capsulated commented on internal/storage/memory.go
> +func (ms *MemStorage) Init(_ context.Context) error {
Этот метод в интерфейсе, да? Лучше убрать, и как написал выше - перенести в конструктор подобные инициализации

2024-07-16 20:37 UTC, capsulated commented on pkg/database/database.go
> +type Database struct {
Интерфейс DB и тип Database немного сбивают с толку... Может DB как-то переименовать? Типа `RetriableDbQueuer` или `RetriableDb`... тут нужно подумать, как лучше, но переименовать, немного уточнив, было бы отлично

2024-07-17 09:13 UTC, moonicy commented on internal/storage/file.go
> +func (fs *FileStorage) Init(ctx context.Context) error {
Нам в Init еще context нужен, но в прошлом ревью вы писали, что контекст плохо передавать в конструктор 
(контекст нужен для WaitShutDown который сохраняет данные в файл при закрытии приложения)

2024-07-17 09:36 UTC, moonicy commented on internal/storage/database.go
> +	sqlStr += "ON CONFLICT (name) DO UPDATE SET value = EXCLUDED.value"
Я не знаю как сделать лучше тут.

2024-07-17 09:37 UTC, moonicy commented on internal/handlers/updates_json_metrics.go
> +	err = mh.storage.SetMetrics(req.Context(), mtCounter, mtGauge)
А не понимаю что тут надо сделать. Мб у вас есть пример?

2024-07-18 13:09 UTC, capsulated commented on internal/storage/file.go
> +func (fs *FileStorage) Init(ctx context.Context) error {
А, тогда да, всё верно! Если контекст, то нужен отдельный метод запуска для передачи контекста. Я предлагаю переименовать метод, может 'Sync`? Это уже по-желанию, смотри как удобнее

2024-07-18 13:16 UTC, capsulated commented on internal/storage/memory.go
> +func (ms *MemStorage) Init(_ context.Context) error {
Пустая реализация метода интерфейсы - это антипаттерн. В следующем спринте попробуй поделить интерфейс ([пример](https://metanit.com/go/tutorial/6.2.php)): методы работы с данными + методы типа ping, sync, close и тп (pinger/closer/syncer). А в местах вызова можно [проверять на соответствие интерфейсу ](https://go.dev/doc/effective_go#blank_implements)

2024-07-18 13:31 UTC, capsulated commented on internal/handlers/updates_json_metrics.go
> +	err = mh.storage.SetMetrics(req.Context(), mtCounter, mtGauge)
Да, конечно
```
ctx, cancel := context.WithCancel(req.Context())
defer cancel()

err = mh.storage.SetMetrics(ctx, mtCounter, mtGauge)
```

Хотя, в данном случае, это наверное даже и лишнее, так как родительский контекст создан клиентом. Но подобный подход нужно знать, особенно когда надо отменить только часть каких-то запросов, а не всю цепочку. Хотя, если захотим на сервере таймаут выставить - то вполне можно сделать и так

2024-07-18 13:44 UTC, capsulated commented on internal/storage/database.go
> +	sqlStr += "ON CONFLICT (name) DO UPDATE SET value = EXCLUDED.value"
С крайнем случае можно собирать строку и делать один запрос - это ещё приемлемо, но не очень хорошее решение (неудобно будет потом с таким запросом). Самое главное, чтобы не по единичному запросу в цикле - это очень плохо))) А вообще в `pgx` есть специальный [инструментарий batch](https://github.com/jackc/pgx/blob/master/batch_test.go)

В [sqlx](https://github.com/jmoiron/sqlx/blob/master/README.md) (тоже хорошая библиотека) есть похожий инструментарий - там непосредственной слайс объектов можно записать одним методом

2024-07-18 13:51 UTC, capsulated approved these changes
На самом деле всё отлично!

Ты большая умница, рассмотрела комментарии, добавила исправления там, применила различные подходы. Приложение уже "вырасло", код хорошо структуирован, правильно разбит на абстрактные слои и ты в нём быстро ориентируешься и вносишь изменения при необходимости. Всё очень достойно 👍💪

Добавил комментарии, скорее для ознакомления. В следующих спринтах можно будет "органично" что-то рефакторить, если будет необходимость

2024-07-19 08:22 UTC, merged