Iteration 25 completed
moonicy/gometrics pull request #25
Opened 2024-11-03 09:11 UTC by moonicy

2024-11-08 00:25 UTC, capsulated requested changes
Добавил пару комментариев, если с чем-то не согласна - как обычно, пиши ответом)) Но главное замечение, хитро спрятанное в введении к спринту: `Важное условие: к концу спринта ваш код должен быть покрыт тестами на 80%` ))))

Если что, задавай вопросы напрямую в директе пачки

2024-11-08 00:25 UTC, capsulated commented on internal/server/grpc.go
> +	return &response, nil
И в таких местах можно возвращать &pb.Metrics (к продолжении к коментарию в proto файле)

2024-11-09 20:14 UTC, moonicy commented on internal/client/client_test.go
> +	cl.SendReport(context.TODO(), report)
Это тест, нет смысла добавлять таймаут

2024-11-09 20:21 UTC, moonicy commented on internal/agent/workerpool/send_metric_worker_pool.go
> +func RunSendReport(cfg config.AgentConfig, client Client, mem *agent.Report, callback func()) func() {
Кажется, что это будет выглядеть как перенос бизнес логики в pkg, что вроде как не очень хорошо.

________
По поводу тестов: запуск сделала через make test (т.к. coverage учитывал сгенерированные протофайлы).
А вообще не совсем понимаю зачем так заморачиваться на 80% покрытия. Я понимаю покрыть 30%, ну 50% в рамках обучения, но 80% выглядит уже как пустая трата времени, которое я могла бы потратить более полезно. 
По факту же в реале нет проектов которые бы на столько покрывали.

2024-11-15 09:24 UTC, merged