Iteration 9 completed
moonicy/gometrics pull request #9
Opened 2024-06-30 11:39 UTC by moonicy

2024-07-02 23:56 UTC, capsulated requested changes
Оставил комментарии. Если есть аргументации в каких-то из замечаний, тогда можно ответить на комментарий с обоснованием принятого решения. Либо на 1-1, если много вопросов или непонятного

2024-07-02 23:56 UTC, capsulated commented on internal/handlers/metrics.go
> +func NewMetricsHandler(mem Storage) *MetricsHandler {
Прям перед конструктором удобно описывать интерфейс, а то искать сложнее

2024-07-02 23:56 UTC, capsulated commented on internal/handlers/route.go
> +	metricsHandler := NewMetricsHandler(st)
Лучше на уровне выше создать все экземпляры, на уровне приложения. Иногда создаётся отдельная пакет `app` и в рамках экземпляра приложения вызываются конструкторы и стартуются подключения, контроллеры, воркеры и тп. В нашем случае это может даже перебор, но в `cmd` лучше перенести все конструкторы и передать эти экземпляры в конструктор роутера. А входной параметром для `storage` у конструктора - интерфейс хранилки:

```go
// Конструкторы
func NewMemStorage(cfg, ....) (Storage, error) {...}
func NewMetricsHandler(store Storage) (*MetricsHandler, error)  {...}

type Route struct {
 	log				*zap.SugaredLogger,
	cfg				*config.ServerConfig,
	fileProducer		*file.Producer
	fileConsumer		*file.Consumer
        metricsHandler	*MetricsHandler
}

func NewRoute(
	log *zap.SugaredLogger,
	cfg *config.ServerConfig,
	pr *file.Producer
	cm *file.Consumer
        metricsHandler *MetricsHandler
) *chi.Mux {
	router := chi.NewRouter()
	...
		r.Post("/", metricsHandler.PostJSONMetricsByName)
	...
}
```

2024-07-02 23:56 UTC, capsulated commented on internal/handlers/update_json_metrics.go
> +func (u *MetricsHandler) UpdateJSONMetrics(res http.ResponseWriter, req *http.Request) {
Имя ресивера расходится, нужно либо `m`, либо `mh` https://go.dev/wiki/CodeReviewComments#receiver-names

2024-07-02 23:56 UTC, capsulated commented on internal/handlers/update_json_metrics.go
> +		http.Error(res, err.Error(), http.StatusBadRequest)
А `http.Error` завершит выполнение хендлера? Выше есть `return`. Нужно проверить, если завершает - то везде убрать return, а если не завершает - то везде добавить

2024-07-02 23:56 UTC, capsulated commented on internal/http/common.go
> +package http
Интересный пакет.  Если добавятся ещё какие-то функции, то можно в `pkg` перенести. А если только в одном пакете используется - то лучше функцию туда перенести, либо сделать методом какого-то из типов, нужно смотреть по ситуации

2024-07-02 23:56 UTC, capsulated commented on internal/http/common.go
> +const DefaultHost = "localhost:8080"
А это, кажется, к конфигу относиться. Лучше оттуда брать дефолтные значения конфигурации

2024-07-02 23:56 UTC, capsulated commented on internal/handlers/route.go
> +func NewRoute(ctx context.Context, log zap.SugaredLogger, cfg config.ServerConfig) *chi.Mux {
Так, а контекст в конструктор передавать не нужно. Контекст передаётся только в первом параметре методов. И нужно, к сожалению, дублировать передачу параметра контекста `ctx` во всем методы. Такой паттерн

2024-07-02 23:56 UTC, capsulated commented on internal/logger/logger.go
> +package logger
Логгер тоже можно в `pkg` из `internal` перенести, чтобы потом также, к примеру, в выпускном использовать

2024-07-02 23:56 UTC, capsulated commented on internal/metrics/metrics.go
> +type Metrics struct {
Не совсем пойму, а почему во множественном числе? Тут же встраивается структура, аналог extend из других языков. И в чём смысл, если можно одну создавать с четырмя полями?

2024-07-02 23:56 UTC, capsulated commented on internal/metrics/metrics.go
> +func (mn MetricName) Validate() error {
А тут ресивер по значению передаётся. Нужно обязательно разобраться когда передавать по ссылке, а когда по значению. В данном случае специально используется передача по значению? Если да, то почему?

2024-07-02 23:56 UTC, capsulated commented on internal/middlewares/gzip.go
> +package middlewares
Мидлвари можно в `pkg` также переносить. Они явно переиспользуемые

2024-07-02 23:56 UTC, capsulated commented on internal/pkg/gzip/gzip.go
> +package gzip
так, а `pkg` должно быть на уровне корня приложения, рядом с `internal`:
```
> internal
> cmd
> pkg
```

2024-07-02 23:56 UTC, capsulated commented on internal/pkg/literaltopointer/literal_to_pointer.go
> +func NewInt(i int64) *int64 {
А это для чего такое? Можно же сразу указатель передать, или наоборот разъименовать без дополнительных функций. Это лишнее

2024-07-02 23:56 UTC, capsulated commented on internal/storage/file.go
> +type Consumer interface {
А нужны ли эти интерфейсы? В приложении планируется разные реализации файл-консьюмера и файл-продюсерра создавать?

2024-07-02 23:56 UTC, capsulated commented on internal/storage/file.go
> +	go func() {
Это лучше убрать из констуктора: скрытая логика обработки закрытия. Тем более `context` не передаётся в конструктор: https://go.dev/wiki/CodeReviewComments#contexts

Это го-рутину надо перенести в `cmd`, либо сделать отдельными методом и запустить в месте вызова констуктора. А `<-ctx.Done()` слушать на уровне сборки/запуска приложения

2024-07-03 11:13 UTC, moonicy commented on internal/agent/report.go
> +	Alloc         = "Alloc"
Там и так по итогу используется мапа, константы нужны просто для удобства понимания какие системные метрики могут прийти от агента. И они также используются в тестах.

2024-07-03 11:16 UTC, moonicy commented on internal/metrics/metrics.go
> +type Metrics struct {
MetricName используется в запросе PostJSONMetricsByName, там не нужны 2 остальных поля. 
Я могу сделать просто одну структуру, но показалось что так более правильно.

2024-07-03 17:19 UTC, moonicy commented on internal/metrics/metrics.go
> +func (mn MetricName) Validate() error {
Здесь используется по значению, т.к. структура не большая и внутри нет ее модификации.

2024-07-08 11:43 UTC, capsulated reviewed
Всё супер! Апрувлю

Оставил несколько комментариев, в виде обсуждения. Если что-то проглядели, пофиксим в следующих спринтах)))

2024-07-08 11:43 UTC, capsulated commented on internal/config/agent.go
> +		ac.ReportInterval, _ = strconv.Atoi(envReportInterval)
А ошибка? Вдруг там символы в переменной окружения, вместо чисел:
```go
func NewAgentConfig() (*AgentConfig, error) {
	ac := AgentConfig{}
	ac.parseFlag()
	return ac
}

func (ac *AgentConfig) parseFlag() error {
	...
	if envReportInterval := os.Getenv("REPORT_INTERVAL"); envReportInterval != "" {
		ac.ReportInterval, err := strconv.Atoi(envReportInterval)
		if err != nil {
				return err
		}
	...
}
```

И конструкторы (в нашем случае `func NewAgentConfig() *AgentConfig {...}` обычно указатель на экземпляр возвращают, если нет необходимости именно по значению возвращать

2024-07-08 11:43 UTC, capsulated commented on internal/config/agent.go
> +		ac.PollInterval, _ = strconv.Atoi(envPollInterval)
Здесь так же, необходимо обработать ошибку (писал об этом в прошлом ревью)

2024-07-08 11:43 UTC, capsulated commented on internal/metrics/metrics.go
> +func (mn MetricName) Validate() error {
Обычно, всегда по указателю передаётся. А когда нужно создать склон объекта (без ссылки на исходный) тогда передают по значению. 

К примеру, в JavaScript всё всегда передаётся по указателю в синтаксисе, а для передачи по значению используется метод `clone`. В питоне, если не ошибаюсь, также

2024-07-08 11:43 UTC, capsulated commented on internal/storage/file.go
> +type Producer interface {
Как уже писал, они лишние. Я думаю, в следующих спринтах можно будет обратить на это внимание, что после удаления этого интерфейса ничего особо не поменяется (а кода станет меньше и разбираться проще :))

2024-07-08 11:43 UTC, capsulated approved these changes

2024-07-08 12:46 UTC, merged